export { getQuiz } from './get_quiz'
export { getQuizzes } from './get_quizzes'
export { getLatestQuizzes } from './get_latest_quizzes'
export { createQuiz } from './create_quiz'
export { updateQuiz } from './update_quiz'
export { deleteQuiz } from './delete_quiz'
